# frozen_string_literal: true

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
# prdct = Product.create [{ name: 'Coffee Cups', price: '7.8', stock_quantity: '8' }]
#   Character.create(name: 'Luke', movie: movies.first)
Product.destroy_all
Category.destroy_all

csv_file = Rails.root + 'db/products.csv'

options = { file_encoding: 'iso-8859-1' } # Only needed if the CSV file was generated by Excel.

products = SmarterCSV.process(csv_file) # Pass the "options" hash as a second argument if CSV was created by Excel.

products.each do |product|
  # Create categories and products here.
  category =  Category.find_or_create_by(name: product[:category])
  puts category.id
  Product.create(
    title: product[:name],
    price: product[:price],
    description: product[:description],
    stock_quantity: product[:stock_quantity],
    category: category
  )
end

# 676.times do
#   product = Product.create(
#     title: Faker::Commerce.product_name,
#     price: Faker::Commerce.price,
#     stock_quantity: Faker::Number.number(digits: 4)
#   )
# end

puts "Product: #{Product.count}"
